# Generated by Django 4.1.2 on 2022-10-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artise',
            new_name='Artiste',
        ),
    ]
