# Generated by Django 4.1.2 on 2022-10-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_lyric_sond_id_alter_song_artiste_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='sond_id',
            new_name='song_id',
        ),
    ]
